package inteviewQuestion.Exception;

import java.sql.SQLException;

public class CustomTest {
	public static void main(String[] args) {
//		try {
//			int x = 10 / 0;
//		} catch (CustomException e) {
//			
//		}

	}

	// void testCase1() throws IOException{

	// try{
	// int x = 10/0;
	// }catch(IOException e) { // same Exception as throws
	// System.out.println(e);
	//// throw new Exception();
	// }finally {
	// System.out.println("Finny Called After Throw");
	// }
	// }
}
